// Tools Catalog - Create & Export Tools Platform
export const tools = [
  {
    id: 'charterpro',
    name: 'CharterPro',
    tagline: 'Project Charter Generator',
    description: 'Create professional project charters in minutes. Define scope, objectives, stakeholders, and deliverables with guided templates.',
    icon: '📋',
    color: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    status: 'live', // live, beta, coming-soon
    category: 'Project Initiation',
    outputFormats: ['PDF', 'Word'],
    features: [
      'Guided charter creation wizard',
      'Professional PDF export',
      'Stakeholder management',
      'Risk assessment templates',
      'Project scope definition',
      'Success criteria tracking'
    ],
    route: '/tools/charterpro',
    launchDate: '2025-06-01',
  },
  {
    id: 'dmaic-generator',
    name: 'DMAIC Generator',
    tagline: 'Six Sigma Project Forms',
    description: 'Structure your continuous improvement projects with professional DMAIC documentation. Define, Measure, Analyze, Improve, Control.',
    icon: '🔄',
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    status: 'beta',
    category: 'Continuous Improvement',
    outputFormats: ['PDF', 'Excel'],
    features: [
      'Complete DMAIC framework',
      'Data collection templates',
      'Root cause analysis tools',
      'Control plan generator',
      'Process capability reports',
      'Professional PDF export'
    ],
    route: '/tools/dmaic-generator',
    launchDate: '2026-Q1',
  },
  {
    id: 'roi-calculator',
    name: 'ROI Calculator',
    tagline: 'Return on Investment Analysis',
    description: 'Calculate and present compelling ROI for your projects and investments. Generate professional financial justification reports.',
    icon: '💰',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
    status: 'beta',
    category: 'Financial Analysis',
    outputFormats: ['PDF', 'Excel'],
    features: [
      'ROI calculation wizard',
      'NPV & IRR analysis',
      'Payback period calculator',
      'Scenario comparison',
      'Executive summary export',
      'Excel financial models'
    ],
    route: '/tools/roi-calculator',
    launchDate: '2026-Q1',
  },
  {
    id: 'tco-calculator',
    name: 'TCO Calculator',
    tagline: 'Total Cost of Ownership',
    description: 'Calculate complete lifecycle costs for IT systems, equipment, and major purchases. Make informed procurement decisions.',
    icon: '🧮',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)',
    status: 'beta',
    category: 'Financial Analysis',
    outputFormats: ['PDF', 'Excel'],
    features: [
      'Lifecycle cost modeling',
      'Vendor comparison',
      'Hidden cost identification',
      'Multi-year projections',
      'Professional reports',
      'Decision matrix export'
    ],
    route: '/tools/tco-calculator',
    launchDate: '2026-Q2',
  },
  {
    id: 'risk-register',
    name: 'Risk Register',
    tagline: 'Risk Assessment & Tracking',
    description: 'Document and assess project risks with professional risk registers. Generate heat maps and mitigation plans.',
    icon: '⚠️',
    color: '#ef4444',
    gradient: 'linear-gradient(135deg, #ef4444 0%, #dc2626 100%)',
    status: 'beta',
    category: 'Risk Management',
    outputFormats: ['PDF', 'Excel'],
    features: [
      'Risk register templates',
      'Probability/impact matrix',
      'Risk heat map generator',
      'Mitigation plan builder',
      'FMEA worksheets',
      'Executive risk summary'
    ],
    route: '/tools/risk-register',
    launchDate: '2026-Q2',
  },
  {
    id: 'feasibility-study',
    name: 'Feasibility Study',
    tagline: 'Investment Justification',
    description: 'Build comprehensive feasibility studies to justify investment decisions. Analyze alternatives, assess risks, and create compelling business cases.',
    icon: '📊',
    color: '#0891b2',
    gradient: 'linear-gradient(135deg, #0891b2 0%, #22d3ee 100%)',
    status: 'beta',
    category: 'Project Initiation',
    outputFormats: ['PDF'],
    features: [
      '16-section guided wizard',
      'Alternative analysis framework',
      'Cost/benefit documentation',
      'Investment analysis (NPV, ROI)',
      'Risk assessment integration',
      'Professional PDF export'
    ],
    route: '/tools/feasibility-study',
    launchDate: '2026-Q1',
  },
  {
    id: 'raci-matrix',
    name: 'RACI Matrix',
    tagline: 'Roles & Responsibilities',
    description: 'Define clear accountability with professional RACI charts. Eliminate confusion about who does what on your projects.',
    icon: '👥',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)',
    status: 'coming-soon',
    category: 'Project Planning',
    outputFormats: ['PDF', 'Excel'],
    features: [
      'RACI chart builder',
      'Role assignment wizard',
      'Stakeholder mapping',
      'Responsibility gaps check',
      'Team communication plan',
      'Multiple export formats'
    ],
    route: '/tools/raci-matrix',
    launchDate: '2026-Q2',
  },
]

// Subscription Plans - New Pricing Model (Jan 2026)
export const plans = [
  {
    id: 'starter',
    name: 'Starter',
    price: 9,
    period: 'month',
    description: 'Access to 1 tool of your choice',
    toolLimit: 1,
    features: [
      'Choose any 1 tool',
      'Unlimited projects',
      'PDF export',
      'Email support',
      'Browse all examples',
    ],
    limitations: [
      'Single tool access',
      'No Excel export',
    ],
    cta: 'Get Started',
    popular: false,
  },
  {
    id: 'professional',
    name: 'Professional',
    price: 19,
    period: 'month',
    description: 'Access to any 5 tools',
    toolLimit: 5,
    features: [
      'Choose any 5 tools',
      'Unlimited projects',
      'PDF & Excel export',
      'Priority support',
      'Custom branding',
    ],
    limitations: [],
    cta: 'Get Started',
    popular: true,
  },
  {
    id: 'unlimited',
    name: 'Unlimited',
    price: 49,
    period: 'month',
    description: 'Access to all current & future tools',
    toolLimit: -1,
    features: [
      'All tools included',
      'All future tools included',
      'Unlimited projects',
      'PDF & Excel export',
      'Priority support',
      'Custom branding',
      'Early access to beta',
    ],
    limitations: [],
    cta: 'Get Started',
    popular: false,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: null,
    period: 'custom',
    description: 'For teams and organizations',
    toolLimit: -1,
    features: [
      'Everything in Unlimited',
      'Unlimited team members',
      'Custom templates',
      'API access',
      'Dedicated support',
      'SSO / SAML',
    ],
    limitations: [],
    cta: 'Contact Sales',
    popular: false,
  },
]

// Helper functions
export const getToolById = (id) => tools.find(t => t.id === id)
export const getLiveTools = () => tools.filter(t => t.status === 'live')
export const getBetaTools = () => tools.filter(t => t.status === 'beta')
export const getComingSoonTools = () => tools.filter(t => t.status === 'coming-soon')
export const getPlanById = (id) => plans.find(p => p.id === id)
export const getToolsByCategory = (category) => tools.filter(t => t.category === category)
